import re
"""
CAM Lease Analyzer Web App — Summary Document Generator

Generates per-tenant and batch summary DOCX documents from pipeline results.
Uses python-docx (already a dependency from the pipeline annotators).
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "Generated by CAM\u2122 \u00b7 Patent Pending \u00b7 "
    "This report is a diagnostic tool and does not constitute legal advice."
)

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]


def _get_resolution_notes(resolutions: Optional[dict], tenant_idx: Optional[int], provision_id: str) -> List[str]:
    if not resolutions or tenant_idx is None or not provision_id:
        return []
    entry = resolutions.get(f"{tenant_idx}:{provision_id}", {}) or {}
    notes = entry.get("notes", []) or []
    note_texts = []
    for note in notes:
        if isinstance(note, dict):
            text = str(note.get("text", "")).strip()
        else:
            text = str(note).strip()
        if text:
            note_texts.append(text)
    return note_texts


def _add_footer(doc: Document) -> None:
    """Add the standard disclaimer footer to all sections."""
    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        p.text = DISCLAIMER
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.runs[0] if p.runs else p.add_run(DISCLAIMER)
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)


def _severity_label(sev: str) -> str:
    """Format severity for display."""
    mapping = {
        "CRITICAL": "\U0001f534 CRITICAL",
        "HIGH": "\u26a0\ufe0f HIGH",
        "MEDIUM": "\u26a0 MEDIUM",
        "LOW": "LOW",
        "CONFORMS": "\u2705 CONFORMS",
    }
    return mapping.get(sev, sev)


def _add_heading_styled(doc: Document, text: str, level: int = 1) -> None:
    """Add a heading with standard styling."""
    doc.add_heading(text, level=level)


def generate_tenant_summary(
    pipeline_results: dict,
    output_path: str,
    resolutions: Optional[dict] = None,
    tenant_idx: Optional[int] = None,
) -> str:
    """Generate a per-tenant summary DOCX document.

    Args:
        pipeline_results: Full pipeline results dict for one tenant.
        output_path: Path to write the DOCX file.

    Returns:
        Path to the generated file.
    """
    doc = Document()

    # Title
    title = doc.add_heading("Contract Analysis Summary", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle with tenant info
    tenant_file = pipeline_results.get("tenant_file", "Unknown")
    template_file = pipeline_results.get("template_file", "Unknown")
    timestamp = pipeline_results.get("timestamp", "")
    try:
        dt = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y")
    except (ValueError, AttributeError):
        date_str = timestamp[:10] if timestamp else "Unknown"

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub.add_run(f"Tenant: {tenant_file}\nAnalysis Date: {date_str}")
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # ── Contract Overview ──
    metadata = pipeline_results.get("contract_metadata", {})
    _add_heading_styled(doc, "Contract Overview", level=1)

    meta_fields = [
        ("Landlord", metadata.get("landlord", "")),
        ("Tenant", metadata.get("tenant", "")),
        ("Property", metadata.get("property_description", "")),
        ("Effective Date", metadata.get("effective_date", "")),
        ("Term", metadata.get("term_length", "")),
        ("Expiration", metadata.get("expiration_date", "")),
        ("Governing Law", metadata.get("governing_law", "")),
        ("Base Rent", metadata.get("base_rent", "")),
        ("Permitted Use", metadata.get("permitted_use", "")),
    ]

    table = doc.add_table(rows=0, cols=2)
    table.style = "Light List Accent 1"
    for label, value in meta_fields:
        if value:
            row = table.add_row()
            row.cells[0].text = label
            row.cells[1].text = value

    if not any(v for _, v in meta_fields):
        doc.add_paragraph(
            "Contract metadata not available. "
            "Run analysis with updated extraction to populate this section."
        )

    # ── Summary Statistics ──
    summary = pipeline_results.get("summary", {})
    _add_heading_styled(doc, "Analysis Summary", level=1)

    stats_text = (
        f"Provisions analyzed: {summary.get('total_provisions_checked', 0)}\n"
        f"Conforming: {summary.get('conforms', 0)}\n"
        f"Deviations found: {summary.get('deviates', 0)}\n"
        f"Unclear: {summary.get('unclear', 0)}"
    )
    doc.add_paragraph(stats_text)

    sev_text = (
        f"Critical: {summary.get('critical', 0)}  |  "
        f"High: {summary.get('high', 0)}  |  "
        f"Medium: {summary.get('medium', 0)}  |  "
        f"Low: {summary.get('low', 0)}"
    )
    doc.add_paragraph(sev_text)

    # ── Deviations ──
    provisions = pipeline_results.get("provisions", [])
    deviations = [p for p in provisions if p.get("final_verdict") == "DEVIATES"]
    deviations.sort(
        key=lambda p: SEVERITY_ORDER.index(p.get("severity", "LOW"))
        if p.get("severity") in SEVERITY_ORDER else 99
    )

    if deviations:
        _add_heading_styled(doc, "Deviations (Review Recommended)", level=1)

        for d in deviations:
            pid = d.get("provision_id", "")
            pname = d.get("provision_name", "")
            sev = d.get("severity", "")
            section_ref = d.get("tenant_section_ref", "")

            heading_text = f"{pid} {pname} \u2014 {sev}"
            if section_ref:
                heading_text += f" \u2014 {section_ref}"
            doc.add_heading(heading_text, level=2)

            # What changed
            challenge = d.get("challenge_details", "")
            sev_reasoning = d.get("severity_reasoning", "")
            if challenge:
                doc.add_paragraph("What Changed:", style="List Bullet")
                doc.add_paragraph(challenge)
            if sev_reasoning:
                doc.add_paragraph("Impact:", style="List Bullet")
                doc.add_paragraph(sev_reasoning)

            # Evaluator info
            pattern = d.get("agreement_pattern", "")
            if pattern:
                doc.add_paragraph(f"Evaluator Agreement: {pattern}")

            # Fragility
            frag = d.get("fragility", {})
            if frag.get("fragile"):
                signals = ", ".join(frag.get("signals", []))
                doc.add_paragraph(f"Fragility Signals: {signals}")

            # Recommended action
            action = d.get("recommended_action", "")
            if action:
                doc.add_paragraph(f"Recommended Action: {action}")
            note_texts = _get_resolution_notes(resolutions, tenant_idx, pid)
            if note_texts:
                doc.add_paragraph("Attorney Notes:")
                for note_text in note_texts:
                    doc.add_paragraph(note_text, style="List Bullet")

            doc.add_paragraph("")  # spacer

    # ── Conforming Provisions ──
    conforming = [p for p in provisions if p.get("final_verdict") == "CONFORMS"]
    if conforming:
        _add_heading_styled(doc, "Conforming Provisions", level=1)
        for c in conforming:
            pid = c.get("provision_id", "")
            pname = c.get("provision_name", "")
            pattern = c.get("agreement_pattern", "")
            doc.add_paragraph(
                f"{pid} {pname} \u2014 {pattern}, conforms",
                style="List Bullet",
            )

    # ── Footer ──
    _add_footer(doc)

    # Save
    doc.save(output_path)
    logger.info(f"Tenant summary saved: {output_path}")
    return output_path


def generate_batch_summary(
    job: dict,
    tenant_results: List[dict],
    output_path: str,
) -> str:
    """Generate a batch summary DOCX covering all tenants.

    Args:
        job: The job dict with metadata.
        tenant_results: List of pipeline results dicts, one per tenant.
        output_path: Path to write the DOCX file.

    Returns:
        Path to the generated file.
    """
    doc = Document()

    # Title
    title = doc.add_heading("Batch Lease Analysis Summary", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Executive Summary ──
    _add_heading_styled(doc, "Executive Summary", level=1)

    template_name = ""
    if tenant_results:
        template_name = tenant_results[0].get("template_file", "Unknown")

    created_at = job.get("created_at", "")
    try:
        dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y at %I:%M %p UTC")
    except (ValueError, AttributeError):
        date_str = created_at

    total_deviations = 0
    highest_severity = "CONFORMS"
    tenants_needing_review = 0
    total_api_calls = 0
    total_elapsed = 0.0

    for tr in tenant_results:
        s = tr.get("summary", {})
        devs = s.get("deviates", 0)
        total_deviations += devs
        if devs > 0:
            tenants_needing_review += 1
        total_api_calls += tr.get("api_calls_total", 0)
        total_elapsed += tr.get("elapsed_sec", 0)

        # Track highest severity
        for sev in SEVERITY_ORDER:
            if s.get(sev.lower(), 0) > 0:
                sev_idx = SEVERITY_ORDER.index(sev)
                curr_idx = SEVERITY_ORDER.index(highest_severity) if highest_severity in SEVERITY_ORDER else 99
                if sev_idx < curr_idx:
                    highest_severity = sev
                break

    exec_text = (
        f"Template: {template_name}\n"
        f"Tenants analyzed: {len(tenant_results)}\n"
        f"Analysis date: {date_str}\n"
        f"Total deviations found: {total_deviations}\n"
        f"Highest severity: {highest_severity}\n"
        f"Tenants requiring review: {tenants_needing_review}\n"
        f"Total API calls: {total_api_calls}\n"
        f"Total processing time: {round(total_elapsed / 60, 1)} minutes"
    )
    doc.add_paragraph(exec_text)

    # ── Comparison Table ──
    if tenant_results:
        _add_heading_styled(doc, "Comparison Table", level=1)

        # Collect all provision IDs from first result (they should be the same)
        provision_ids = []
        provision_names = {}
        if tenant_results[0].get("provisions"):
            for p in tenant_results[0]["provisions"]:
                pid = p.get("provision_id", "")
                provision_ids.append(pid)
                provision_names[pid] = p.get("provision_name", pid)

        if provision_ids:
            # Build table: header row + one row per tenant
            num_cols = min(len(provision_ids) + 1, 10)  # limit columns for readability
            shown_pids = provision_ids[:num_cols - 1]

            table = doc.add_table(rows=1 + len(tenant_results), cols=len(shown_pids) + 1)
            table.style = "Table Grid"
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            # Header
            hdr = table.rows[0]
            hdr.cells[0].text = "Tenant"
            for ci, pid in enumerate(shown_pids):
                hdr.cells[ci + 1].text = pid

            # Data rows
            for ri, tr in enumerate(tenant_results):
                row = table.rows[ri + 1]
                row.cells[0].text = tr.get("tenant_file", f"Tenant {ri + 1}")[:20]

                prov_map = {p["provision_id"]: p for p in tr.get("provisions", [])}
                for ci, pid in enumerate(shown_pids):
                    p = prov_map.get(pid, {})
                    verdict = p.get("final_verdict", "\u2014")
                    sev = p.get("severity", "")
                    if verdict == "CONFORMS":
                        row.cells[ci + 1].text = "\u2705"
                    elif verdict == "DEVIATES":
                        row.cells[ci + 1].text = sev or "DEV"
                    else:
                        row.cells[ci + 1].text = "\u2014"

            # If more provisions than shown
            if len(provision_ids) > len(shown_pids):
                doc.add_paragraph(
                    f"(Showing {len(shown_pids)} of {len(provision_ids)} provisions)"
                )

    # ── Per-Tenant Highlights ──
    _add_heading_styled(doc, "Per-Tenant Highlights", level=1)

    # Sort by risk (most deviations first)
    sorted_results = sorted(
        tenant_results,
        key=lambda tr: tr.get("summary", {}).get("deviates", 0),
        reverse=True,
    )

    for tr in sorted_results:
        tenant_file = tr.get("tenant_file", "Unknown")
        s = tr.get("summary", {})
        devs = s.get("deviates", 0)
        conforms = s.get("conforms", 0)

        doc.add_heading(tenant_file, level=2)

        if devs == 0:
            doc.add_paragraph(
                f"All {conforms} provisions conform to the standard template. "
                "No deviations detected."
            )
        else:
            # List deviations
            deviations = [
                p for p in tr.get("provisions", [])
                if p.get("final_verdict") == "DEVIATES"
            ]
            deviations.sort(
                key=lambda p: SEVERITY_ORDER.index(p.get("severity", "LOW"))
                if p.get("severity") in SEVERITY_ORDER else 99
            )

            lines = []
            for d in deviations:
                pid = d.get("provision_id", "")
                pname = d.get("provision_name", "")
                sev = d.get("severity", "")
                lines.append(f"{pid} {pname} ({sev})")

            doc.add_paragraph(
                f"{devs} deviation(s) found, {conforms} conforming:"
            )
            for line in lines:
                doc.add_paragraph(line, style="List Bullet")

    # ── Footer ──
    _add_footer(doc)

    # Save
    doc.save(output_path)
    logger.info(f"Batch summary saved: {output_path}")
    return output_path


# ══════════════════════════════════════════════════════
# Combined Synopsis PDF (ReportLab flowable-based layout)
# ══════════════════════════════════════════════════════

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT, TA_CENTER


# ── Smart quote sanitization ──

def _sanitize_for_pdf(text: str) -> str:
    """Replace smart quotes and other Unicode chars that Helvetica can't render."""
    if not text:
        return text
    replacements = {
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u201C': '"',   # left double quote
        '\u201D': '"',   # right double quote
        '\u2013': '-',   # en dash
        '\u2014': '--',  # em dash
        '\u2026': '...',  # ellipsis
        '\u00A0': ' ',   # non-breaking space
        '\u2010': '-',   # hyphen
        '\u2011': '-',   # non-breaking hyphen
        '\u2012': '-',   # figure dash
        '\u2015': '--',  # horizontal bar
        '\u2032': "'",   # prime
        '\u2033': '"',   # double prime
        '\u00B7': '-',   # middle dot
    }
    for unicode_char, replacement in replacements.items():
        text = text.replace(unicode_char, replacement)
    # Strip markdown bold/italic markers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # **bold** -> bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)        # *italic* -> italic
    text = re.sub(r'__(.+?)__', r'\1', text)          # __bold__ -> bold
    text = re.sub(r'_(.+?)_', r'\1', text)            # _italic_ -> italic
    return text


def _esc_xml(text: str) -> str:
    """Escape text for ReportLab Paragraph XML and sanitize smart quotes."""
    text = _sanitize_for_pdf(text or "")
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ── Model display names ──

_MODEL_DISPLAY_NAMES = {
    "gemini-3.1-pro-preview": "Gemini 3.1 Pro (Google)",
    "gemini-2.5-pro": "Gemini 2.5 Pro (Google)",
    "gemini-2.5-flash": "Gemini 2.5 Flash (Google)",
    "gemini-2.0-flash": "Gemini 2.0 Flash (Google)",
    "claude-sonnet-4-20250514": "Claude Sonnet 4 (Anthropic)",
    "gpt-5.2": "GPT-5.2 (OpenAI)",
    "grok-3": "Grok 3 (xAI)",
}


def _model_name(model_id: str) -> str:
    return _MODEL_DISPLAY_NAMES.get(model_id, model_id or "Unknown")


def _format_tenant_name(filename: str) -> str:
    """Format tenant filename for display: strip extension, prettify."""
    stem = Path(filename).stem if filename else "Unknown"
    parts = stem.split("_", 1)
    if len(parts) == 2:
        return f"{parts[0]} ({parts[1]})"
    return stem


# ── ReportLab styles ──

def _build_styles():
    """Build all paragraph styles for the synopsis PDF."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        "SynopsisTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=HexColor("#1a365d"),
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "SynopsisSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=HexColor("#64748b"),
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "SynopsisHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=18,
        textColor=HexColor("#1a365d"),
        spaceBefore=16,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "TenantHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=16,
        textColor=HexColor("#1e293b"),
        spaceBefore=6,
        spaceAfter=4,
    ))
    # Override built-in BodyText (getSampleStyleSheet already includes one)
    styles["BodyText"].fontName = "Helvetica"
    styles["BodyText"].fontSize = 9.5
    styles["BodyText"].leading = 13
    styles["BodyText"].textColor = HexColor("#1e293b")
    styles["BodyText"].spaceAfter = 4
    styles.add(ParagraphStyle(
        "BodyBold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=13,
        textColor=HexColor("#1e293b"),
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "ClauseLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=12,
        textColor=HexColor("#64748b"),
        leftIndent=16,
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "ClauseText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=HexColor("#1e293b"),
        leftIndent=16,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "Conforming",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=HexColor("#16a34a"),
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "SmallMuted",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=HexColor("#64748b"),
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=HexColor("#64748b"),
        spaceBefore=12,
        spaceAfter=0,
    ))
    # Deal overview styles (Step 039L)
    styles.add(ParagraphStyle(
        "DealLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=13,
        textColor=HexColor("#64748b"),
        spaceAfter=0,
    ))
    styles.add(ParagraphStyle(
        "DealValue",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=HexColor("#1e293b"),
        leftIndent=110,
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "DealRow",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=HexColor("#1e293b"),
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "KeyTermBullet",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=HexColor("#1e293b"),
        leftIndent=24,
        bulletIndent=12,
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        "FindingHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=15,
        textColor=HexColor("#1e293b"),
        spaceBefore=10,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "FindingBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13.5,
        textColor=HexColor("#1e293b"),
        leftIndent=8,
        spaceAfter=3,
    ))
    styles.add(ParagraphStyle(
        "FindingAction",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=9,
        leading=13,
        textColor=HexColor("#475569"),
        leftIndent=8,
        spaceAfter=8,
    ))

    return styles


_SEV_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#c2410c",
    "MEDIUM": "#d97706",
    "LOW": "#64748b",
}


def _get_highest_severity(summary: dict) -> str:
    """Return the highest severity found in a summary dict."""
    for sev in SEVERITY_ORDER:
        if summary.get(sev.lower(), 0) > 0:
            return sev
    return "CONFORMS"


def generate_combined_summary_pdf(
    job: dict,
    tenant_results: List[dict],
    output_path: str,
) -> str:
    """Generate a single combined synopsis PDF covering all tenants.

    Uses ReportLab flowables for automatic page breaks — no manual Y tracking.

    Args:
        job: The job dict with metadata.
        tenant_results: List of pipeline results dicts, one per tenant.
        output_path: Path to write the PDF file.

    Returns:
        Path to the generated file.
    """
    try:
        return _generate_combined_synopsis_inner(job, tenant_results, output_path)
    except Exception as e:
        logger.error(f"Synopsis PDF layout failed ({e}), generating fallback...")
        return _generate_fallback_synopsis_pdf(job, tenant_results, output_path)


def _generate_fallback_synopsis_pdf(
    job: dict,
    tenant_results: List[dict],
    output_path: str,
) -> str:
    """Minimal fallback PDF if the flowable layout fails."""
    styles = _build_styles()
    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=72, rightMargin=72, topMargin=72, bottomMargin=72,
    )
    elements = []
    elements.append(Paragraph("CAM ANALYSIS SYNOPSIS", styles["SynopsisTitle"]))
    elements.append(Paragraph("(Simplified layout)", styles["SynopsisSubtitle"]))
    elements.append(Spacer(1, 10))

    for tenant_idx, tr in enumerate(tenant_results):
        tenant_file = tr.get("tenant_file", "Unknown")
        s = tr.get("summary", {})
        devs = s.get("deviates", 0)
        conforms = s.get("conforms", 0)

        elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0")))
        elements.append(Paragraph(_esc_xml(tenant_file), styles["TenantHeading"]))
        elements.append(Paragraph(f"Deviations: {devs}, Conforming: {conforms}", styles["BodyText"]))

        provisions = tr.get("provisions", [])
        deviations = [p for p in provisions if p.get("final_verdict") == "DEVIATES"]
        deviations.sort(
            key=lambda p: SEVERITY_ORDER.index(p.get("severity", "LOW"))
            if p.get("severity") in SEVERITY_ORDER else 99
        )
        for d in deviations:
            pid = d.get("provision_id", "")
            pname = d.get("provision_name", "")
            sev = d.get("severity", "")
            summary_text = d.get("challenge_details") or d.get("severity_reasoning") or ""
            elements.append(Paragraph(
                f"{_esc_xml(pid)} {_esc_xml(pname)} ({_esc_xml(sev)}): {_esc_xml(summary_text)}",
                styles["ClauseText"],
            ))
            for note_text in _get_resolution_notes(job.get("resolutions", {}), tenant_idx, pid):
                elements.append(Paragraph(
                    f"<b>Attorney Note:</b> {_esc_xml(note_text)}",
                    styles["ClauseText"],
                ))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(_sanitize_for_pdf(DISCLAIMER), styles["Disclaimer"]))
    doc.build(elements)
    logger.info(f"Fallback synopsis PDF saved: {output_path}")
    return output_path


def _generate_combined_synopsis_inner(
    job: dict,
    tenant_results: List[dict],
    output_path: str,
) -> str:
    """Lawyer-facing synopsis PDF using ReportLab flowables.

    Layout (Step 039L restructure):
      Page 1:   Deal Overview (parties, property, rent, term, key terms)
                Analysis Results (deviation counts, severity breakdown)
      Page 2+:  Findings per tenant — plain language memo style
                (risk_headline lead, plain English explanation, recommended action)
      Last pg:  Technical Appendix (models, timing, pipeline version)
    """
    styles = _build_styles()

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=72, rightMargin=72, topMargin=72, bottomMargin=72,
    )
    elements = []

    # ── Gather metadata from first tenant ──
    first_result = tenant_results[0] if tenant_results else {}
    deal = first_result.get("deal_overview", {})
    meta = first_result.get("contract_metadata", {})
    models_used = first_result.get("models_used", {})

    created_at = job.get("created_at", "")
    try:
        dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y")
    except (ValueError, AttributeError):
        date_str = created_at[:10] if created_at else "Unknown"

    job_id = job.get("job_id", "")

    # ── Aggregate stats ──
    total_deviations = 0
    total_provisions = 0
    sev_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    total_api_calls = 0
    total_elapsed = 0.0

    for tr in tenant_results:
        s = tr.get("summary", {})
        total_deviations += s.get("deviates", 0)
        total_provisions += s.get("total_provisions_checked", 0)
        total_api_calls += tr.get("api_calls_total", 0)
        total_elapsed += tr.get("elapsed_sec", 0)
        for sev in sev_counts:
            sev_counts[sev] += s.get(sev.lower(), 0)

    # ════════════════════════════════════════════════
    # PAGE 1: HEADER + DEAL OVERVIEW + ANALYSIS RESULTS
    # ════════════════════════════════════════════════

    elements.append(Paragraph("CAM ANALYSIS SYNOPSIS", styles["SynopsisTitle"]))
    subtitle_parts = [_esc_xml(date_str)]
    if job_id:
        subtitle_parts.append(_esc_xml(job_id))
    elements.append(Paragraph(" | ".join(subtitle_parts), styles["SynopsisSubtitle"]))
    elements.append(Spacer(1, 10))

    # ── Deal Overview section ──
    elements.append(HRFlowable(width="100%", thickness=1.5, color=HexColor("#1a365d"),
                                spaceBefore=2, spaceAfter=6))
    elements.append(Paragraph("REFERENCE DOCUMENT OVERVIEW", styles["SynopsisHeading"]))
    elements.append(Paragraph(
        "<i>Standard template -- deviations from these terms are flagged below</i>",
        styles["SmallMuted"],
    ))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=HexColor("#1a365d"),
                                spaceBefore=2, spaceAfter=8))

    # Build deal overview rows from deal_overview (preferred) or fall back to contract_metadata
    landlord = deal.get("landlord_name") or meta.get("landlord", "")
    tenant_name = deal.get("tenant_name") or meta.get("tenant", "")
    property_addr = deal.get("property_address") or meta.get("property_description", "")
    property_type = deal.get("property_type", "")
    lease_term = deal.get("lease_term_years")
    commencement = deal.get("commencement_date") or meta.get("effective_date", "")
    expiration = deal.get("expiration_date") or meta.get("expiration_date", "")
    renewal = deal.get("renewal_options", "")
    base_rent = deal.get("base_rent_monthly") or meta.get("base_rent", "")
    escalation = deal.get("escalation", "")
    security = deal.get("security_deposit", "")
    cam_structure = deal.get("cam_structure", "")
    permitted_use = deal.get("permitted_use") or meta.get("permitted_use", "")
    key_terms = deal.get("key_terms_summary", [])

    # Format term string
    term_str = ""
    if lease_term:
        term_str = f"{lease_term} year{'s' if lease_term != 1 else ''}"
        if commencement and expiration:
            term_str += f" ({commencement} -- {expiration})"
        elif commencement:
            term_str += f" (from {commencement})"
    elif meta.get("term_length"):
        term_str = meta.get("term_length", "")
        if commencement:
            term_str += f" (from {commencement})"

    # Parties
    if landlord and tenant_name:
        parties_str = f"{landlord} (Landlord) / {tenant_name} (Tenant)"
    elif landlord:
        parties_str = f"Landlord: {landlord}"
    elif tenant_name:
        parties_str = f"Tenant: {tenant_name}"
    else:
        parties_str = ""

    # Render deal overview as label: value rows
    deal_rows = [
        ("Parties", parties_str),
        ("Property", property_addr),
        ("Lease Type", property_type),
        ("Term", term_str),
        ("Renewal", renewal),
        ("Rent", base_rent),
        ("Escalation", escalation),
        ("Security", security),
        ("CAM/OpEx", cam_structure),
        ("Permitted Use", permitted_use),
    ]

    has_any_deal_data = any(v for _, v in deal_rows)
    if has_any_deal_data:
        for label, value in deal_rows:
            if value:
                elements.append(Paragraph(
                    f'<b>{_esc_xml(label)}:</b>  {_esc_xml(str(value))}',
                    styles["DealRow"],
                ))

        # Key Terms bullets
        if key_terms:
            elements.append(Spacer(1, 4))
            elements.append(Paragraph("<b>Key Terms:</b>", styles["DealRow"]))
            for term in key_terms:
                if term:
                    elements.append(Paragraph(
                        f"&bull; {_esc_xml(term)}",
                        styles["KeyTermBullet"],
                    ))
    else:
        elements.append(Paragraph(
            "Deal overview not available. Run analysis with updated extraction to populate this section.",
            styles["BodyText"],
        ))

    elements.append(Spacer(1, 14))

    # ── Run Synopsis summary ──
    elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                spaceBefore=4, spaceAfter=6))
    elements.append(Paragraph("RUN SYNOPSIS", styles["SynopsisHeading"]))

    elements.append(Paragraph(
        f"{total_deviations} deviation{'s' if total_deviations != 1 else ''} "
        f"found across {total_provisions} provisions analyzed",
        styles["BodyBold"],
    ))
    if len(tenant_results) > 1:
        elements.append(Paragraph(f"Tenants reviewed: {len(tenant_results)}", styles["BodyText"]))

    sev_parts = []
    for sev_label in SEVERITY_ORDER:
        count = sev_counts.get(sev_label, 0)
        if count > 0:
            sev_parts.append(f"{count} {sev_label}")
    if sev_parts:
        elements.append(Paragraph(" | ".join(sev_parts), styles["BodyText"]))

    elements.append(Spacer(1, 12))

    # ── Provision Checklist (traffic-light grid, matches screen) ──
    # For single tenant, show from the first result; for multi-tenant, aggregate
    all_provisions_for_checklist = []
    if len(tenant_results) == 1:
        all_provisions_for_checklist = tenant_results[0].get("provisions", [])
    else:
        # Aggregate: show each provision once with worst severity across tenants
        prov_worst = {}  # pid -> provision dict (with worst severity)
        for tr in tenant_results:
            for p in tr.get("provisions", []):
                pid = p.get("provision_id", "")
                if not pid:
                    continue
                if pid not in prov_worst:
                    prov_worst[pid] = dict(p)
                else:
                    existing = prov_worst[pid]
                    # Upgrade verdict
                    if p.get("final_verdict") == "DEVIATES" and existing.get("final_verdict") != "DEVIATES":
                        prov_worst[pid] = dict(p)
                    elif p.get("final_verdict") == "DEVIATES" and existing.get("final_verdict") == "DEVIATES":
                        # Keep higher severity
                        e_idx = SEVERITY_ORDER.index(existing.get("severity", "LOW")) if existing.get("severity") in SEVERITY_ORDER else 99
                        p_idx = SEVERITY_ORDER.index(p.get("severity", "LOW")) if p.get("severity") in SEVERITY_ORDER else 99
                        if p_idx < e_idx:
                            prov_worst[pid] = dict(p)
                    elif p.get("final_verdict") == "UNCLEAR" and existing.get("final_verdict") == "CONFORMS":
                        prov_worst[pid] = dict(p)
        all_provisions_for_checklist = list(prov_worst.values())

    if all_provisions_for_checklist:
        elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                    spaceBefore=4, spaceAfter=6))
        elements.append(Paragraph("PROVISION CHECKLIST", styles["SynopsisHeading"]))

        # Group by severity bucket
        sev_groups = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": [], "CONFORMS": [], "UNCLEAR": []}
        for p in all_provisions_for_checklist:
            verdict = p.get("final_verdict", "")
            if verdict == "DEVIATES":
                sev = p.get("severity", "MEDIUM")
                if sev in sev_groups:
                    sev_groups[sev].append(p)
                else:
                    sev_groups["MEDIUM"].append(p)
            elif verdict == "UNCLEAR":
                sev_groups["UNCLEAR"].append(p)
            else:
                sev_groups["CONFORMS"].append(p)

        sev_icons = {"CRITICAL": "\u2715", "HIGH": "\u25cf", "MEDIUM": "\u25cb", "LOW": "\u2013", "CONFORMS": "\u2713", "UNCLEAR": "\u25ca"}
        sev_checklist_colors = {
            "CRITICAL": "#dc2626", "HIGH": "#c2410c", "MEDIUM": "#d97706",
            "LOW": "#64748b", "CONFORMS": "#16a34a", "UNCLEAR": "#7c3aed",
        }
        for sev_key in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNCLEAR", "CONFORMS"]:
            items = sev_groups.get(sev_key, [])
            if not items:
                continue
            color = sev_checklist_colors.get(sev_key, "#64748b")
            icon = sev_icons.get(sev_key, "[-]")
            label = "Needs Review" if sev_key == "UNCLEAR" else sev_key.title()
            names = ", ".join(
                f"{_esc_xml(p.get('provision_id', ''))} {_esc_xml(p.get('provision_name', ''))}"
                for p in items
            )
            elements.append(Paragraph(
                f'<font color="{color}"><b>{icon} {label}:</b></font>  {names}',
                styles["BodyText"],
            ))

        elements.append(Spacer(1, 8))

    # ── Batch Summary Table (multi-tenant only, matches screen) ──
    if len(tenant_results) > 1:
        elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                    spaceBefore=4, spaceAfter=6))
        elements.append(Paragraph("CONTRACT STATUS SNAPSHOT", styles["SynopsisHeading"]))

        # Sort by severity (most severe first)
        batch_sorted = sorted(
            tenant_results,
            key=lambda tr: (
                SEVERITY_ORDER.index(_get_highest_severity(tr.get("summary", {})))
                if _get_highest_severity(tr.get("summary", {})) in SEVERITY_ORDER else 99
            ),
        )

        for tr in batch_sorted:
            t_name = _format_tenant_name(tr.get("tenant_file", "Unknown"))
            s = tr.get("summary", {})
            devs = s.get("deviates", 0)
            highest = _get_highest_severity(s)

            if s.get("critical", 0) > 0:
                action = "Immediate"
            elif s.get("high", 0) > 0:
                action = "Review"
            elif devs > 0:
                action = "Monitor"
            else:
                action = "No action"

            sev_color = _SEV_COLORS.get(highest, "#16a34a")
            elements.append(Paragraph(
                f'{_esc_xml(t_name)}:  {devs} deviation{"s" if devs != 1 else ""}  |  '
                f'<font color="{sev_color}"><b>{_esc_xml(highest)}</b></font>  |  '
                f'{_esc_xml(action)}',
                styles["BodyText"],
            ))

        elements.append(Spacer(1, 8))

    # ── Cross-Contract Issue Matrix (multi-tenant only) ──
    if len(tenant_results) > 1:
        # Aggregate: for each provision_id, which tenants have it as DEVIATES?
        issue_map = {}  # pid -> { pname, severity, tenants: [filename] }
        clean_tenants = []
        for tr in tenant_results:
            tenant_file = _format_tenant_name(tr.get("tenant_file", "Unknown"))
            has_deviation = False
            for p in tr.get("provisions", []):
                if p.get("final_verdict") == "DEVIATES":
                    has_deviation = True
                    pid = p.get("provision_id", "")
                    if pid not in issue_map:
                        issue_map[pid] = {
                            "pname": p.get("provision_name", pid),
                            "severity": p.get("severity", "MEDIUM"),
                            "tenants": [],
                        }
                    # Track highest severity across tenants
                    existing_idx = SEVERITY_ORDER.index(issue_map[pid]["severity"]) if issue_map[pid]["severity"] in SEVERITY_ORDER else 99
                    this_idx = SEVERITY_ORDER.index(p.get("severity", "MEDIUM")) if p.get("severity", "MEDIUM") in SEVERITY_ORDER else 99
                    if this_idx < existing_idx:
                        issue_map[pid]["severity"] = p.get("severity", "MEDIUM")
                    issue_map[pid]["tenants"].append(tenant_file)
            if not has_deviation:
                clean_tenants.append(tenant_file)

        if issue_map or clean_tenants:
            elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                        spaceBefore=4, spaceAfter=6))
            elements.append(Paragraph("CROSS-CONTRACT ISSUE MATRIX", styles["SynopsisHeading"]))

            issues = sorted(
                issue_map.items(),
                key=lambda x: SEVERITY_ORDER.index(x[1]["severity"]) if x[1]["severity"] in SEVERITY_ORDER else 99,
            )
            sev_markers = {"CRITICAL": "[!]", "HIGH": "[!]", "MEDIUM": "[*]", "LOW": "[-]"}
            for pid, info in issues:
                sev = info["severity"]
                sev_color = _SEV_COLORS.get(sev, "#64748b")
                marker = sev_markers.get(sev, "[-]")
                pname_short = (info["pname"] or "").split(" ", 1)[-1] if info["pname"] else ""
                tenant_list = ", ".join(info["tenants"])
                elements.append(Paragraph(
                    f'<font color="{sev_color}"><b>{marker} {_esc_xml(pid)} {_esc_xml(pname_short)}</b></font>'
                    f'  --  {_esc_xml(tenant_list)}',
                    styles["BodyText"],
                ))

            if clean_tenants:
                elements.append(Paragraph(
                    f'<font color="#16a34a"><b>[OK] All provisions conform</b></font>'
                    f'  --  {_esc_xml(", ".join(clean_tenants))}',
                    styles["BodyText"],
                ))

            elements.append(Spacer(1, 8))

    # ════════════════════════════════════════════════
    # PAGE 2+: Contract Findings (plain language, per contract)
    # ════════════════════════════════════════════════

    elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                spaceBefore=4, spaceAfter=6))
    # ════════════════════════════════════════════════
    # COVERAGE & GAPS SECTION
    # ════════════════════════════════════════════════

    # Collect coverage issues across all tenants
    coverage_issues = []
    for tr in tenant_results:
        ca = tr.get("coverage_assessment", [])
        tenant_file = tr.get("tenant_file", "")
        for item in ca:
            state = item.get("coverage_state", "covered")
            if state in ("missing", "partial", "covered_unfavorable"):
                coverage_issues.append({
                    "pid": item.get("issue_area_id", ""),
                    "name": item.get("provision_name", item.get("issue_area_id", "")),
                    "state": state,
                    "materiality": item.get("materiality", "medium"),
                    "exposure": item.get("exposure_statement", ""),
                    "tenant": tenant_file,
                    "elements_missing": item.get("elements_missing", []),
                })

    if coverage_issues:
        # Sort: high materiality first
        mat_order = {"high": 0, "medium": 1, "low": 2}
        coverage_issues.sort(key=lambda x: mat_order.get(x["materiality"], 1))

        elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                   spaceBefore=12, spaceAfter=8))
        elements.append(Paragraph("COVERAGE & GAPS", styles["SynopsisHeading"]))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            "The following provisions were present but incomplete, unfavorable, or missing entirely.",
            styles["FindingBody"],
        ))
        elements.append(Spacer(1, 6))

        state_labels = {
            "missing": "MISSING",
            "partial": "INCOMPLETE",
            "covered_unfavorable": "UNFAVORABLE TERMS",
        }
        state_colors = {
            "missing": "#c2410c",
            "partial": "#856404",
            "covered_unfavorable": "#0369a1",
        }
        mat_icons = {"high": "!", "medium": "~", "low": "-"}

        for issue in coverage_issues:
            state = issue["state"]
            label = state_labels.get(state, state.upper())
            color = state_colors.get(state, "#64748b")
            icon = mat_icons.get(issue["materiality"], "~")
            pid = issue["pid"]
            name = issue["name"] or pid
            exposure = _sanitize_for_pdf(issue["exposure"] or "")
            missing_els = issue.get("elements_missing", [])

            # Heading line
            heading_line = (
                f'[{icon}] <font color="{color}"><b>{_esc_xml(pid)} {_esc_xml(name)}</b></font>'
                f' <font color="#64748b">— {_esc_xml(label)}</font>'
            )
            elements.append(Paragraph(heading_line, styles["FindingBody"]))

            # Missing elements if any
            if missing_els:
                missing_str = ", ".join(_esc_xml(str(e)) for e in missing_els[:5])
                elements.append(Paragraph(
                    f'<i>Missing: {missing_str}</i>',
                    styles["ClauseText"],
                ))

            # Exposure statement
            if exposure:
                elements.append(Paragraph(_esc_xml(exposure), styles["ClauseText"]))

            elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 6))

    # ════════════════════════════════════════════════
    # COVERAGE & GAPS SECTION
    # ════════════════════════════════════════════════
    coverage_issues = []
    for tr in tenant_results:
        ca = tr.get("coverage_assessment", [])
        for item in ca:
            state = item.get("coverage_state", "covered")
            if state in ("missing", "partial", "covered_unfavorable"):
                coverage_issues.append({
                    "pid": item.get("issue_area_id", ""),
                    "name": item.get("provision_name", item.get("issue_area_id", "")),
                    "state": state,
                    "materiality": item.get("materiality", "medium"),
                    "exposure": item.get("exposure_statement", ""),
                    "elements_missing": item.get("elements_missing", []),
                })

    if coverage_issues:
        mat_order = {"high": 0, "medium": 1, "low": 2}
        coverage_issues.sort(key=lambda x: mat_order.get(x["materiality"], 1))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                   spaceBefore=12, spaceAfter=8))
        elements.append(Paragraph("COVERAGE & GAPS", styles["SynopsisHeading"]))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            "The following provisions were present but incomplete, unfavorable, or missing entirely.",
            styles["FindingBody"],
        ))
        elements.append(Spacer(1, 6))
        state_labels = {"missing": "MISSING", "partial": "INCOMPLETE", "covered_unfavorable": "UNFAVORABLE TERMS"}
        state_colors = {"missing": "#c2410c", "partial": "#856404", "covered_unfavorable": "#0369a1"}
        mat_icons = {"high": "!", "medium": "~", "low": "-"}
        for issue in coverage_issues:
            state = issue["state"]
            label = state_labels.get(state, state.upper())
            color = state_colors.get(state, "#64748b")
            icon = mat_icons.get(issue["materiality"], "~")
            pid = issue["pid"]
            name = issue["name"] or pid
            exposure = _sanitize_for_pdf(issue["exposure"] or "")
            missing_els = issue.get("elements_missing", [])
            heading_line = (
                f'[{icon}] <font color="{color}"><b>{_esc_xml(pid)} {_esc_xml(name)}</b></font>'
                f' <font color="#64748b">-- {_esc_xml(label)}</font>'
            )
            elements.append(Paragraph(heading_line, styles["FindingBody"]))
            if missing_els:
                missing_str = ", ".join(_esc_xml(str(e)) for e in missing_els[:5])
                elements.append(Paragraph(f'<i>Missing elements: {missing_str}</i>', styles["ClauseText"]))
            if exposure:
                elements.append(Paragraph(_esc_xml(exposure), styles["ClauseText"]))
            elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 6))

    elements.append(Paragraph("CONTRACT FINDINGS", styles["SynopsisHeading"]))

    sorted_results = sorted(
        tenant_results,
        key=lambda tr: tr.get("summary", {}).get("deviates", 0),
        reverse=True,
    )

    for tr in sorted_results:
        tenant_idx = tenant_results.index(tr)
        tenant_file = tr.get("tenant_file", "Unknown")
        tenant_display = _format_tenant_name(tenant_file)
        s = tr.get("summary", {})
        devs = s.get("deviates", 0)
        total = s.get("total_provisions_checked", 0)

        # Show tenant heading only for multi-tenant batches
        if len(tenant_results) > 1:
            elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                        spaceBefore=10, spaceAfter=4))
            elements.append(Paragraph(f"TENANT: {_esc_xml(tenant_display)}", styles["TenantHeading"]))

            # Per-tenant contract metadata (matches screen's Contract Summary section)
            t_meta = tr.get("contract_metadata", {})
            t_deal = tr.get("deal_overview", {})
            t_landlord = t_deal.get("landlord_name") or t_meta.get("landlord", "")
            t_tenant_name = t_deal.get("tenant_name") or t_meta.get("tenant", "")
            t_property = t_deal.get("property_address") or t_meta.get("property_description", "")
            t_rent = t_deal.get("base_rent_monthly") or t_meta.get("base_rent", "")
            t_term = t_meta.get("term_length", "")
            t_permitted = t_deal.get("permitted_use") or t_meta.get("permitted_use", "")

            meta_rows = []
            if t_landlord:   meta_rows.append(f"Landlord: {t_landlord}")
            if t_tenant_name: meta_rows.append(f"Tenant: {t_tenant_name}")
            if t_property:   meta_rows.append(f"Property: {t_property}")
            if t_rent:       meta_rows.append(f"Base Rent: {t_rent}")
            if t_term:       meta_rows.append(f"Term: {t_term}")
            if t_permitted:  meta_rows.append(f"Permitted Use: {t_permitted}")

            if meta_rows:
                elements.append(Paragraph(
                    _esc_xml("  |  ".join(meta_rows)),
                    styles["SmallMuted"],
                ))

        # List deviations and unclear sorted by severity — memo style
        provisions = tr.get("provisions", [])
        findings = [p for p in provisions
                     if p.get("final_verdict") in ("DEVIATES", "UNCLEAR")]

        if not findings:
            elements.append(Paragraph(
                f"All {total} provisions conform to the standard template. No deviations detected.",
                styles["Conforming"],
            ))
            continue
        findings.sort(
            key=lambda p: SEVERITY_ORDER.index(p.get("severity", "LOW"))
            if p.get("severity") in SEVERITY_ORDER else 99
        )

        for d in findings:
            pid = d.get("provision_id", "")
            pname = d.get("provision_name", "")
            sev = d.get("severity", "")
            is_unclear = d.get("final_verdict") == "UNCLEAR"
            risk_headline = d.get("risk_headline", "")
            challenge_details = d.get("challenge_details", "")
            sev_reasoning = d.get("severity_reasoning", "")
            financial_impact = d.get("financial_impact", "")
            action = d.get("recommended_action", "")
            note_texts = _get_resolution_notes(job.get("resolutions", {}), tenant_idx, pid)
            section_ref = d.get("tenant_section_ref", "")
            agreement_pattern = d.get("agreement_pattern", "")
            template_text = d.get("template_text", "")
            tenant_text = d.get("tenant_text", "")

            # Display label: "Needs Review" for UNCLEAR, severity for DEVIATES
            display_sev = "Needs Review" if is_unclear else sev
            sev_color = "#7c3aed" if is_unclear else _SEV_COLORS.get(sev, "#64748b")

            # Memo-style finding: heading, then plain English body
            finding_els = []

            # Heading: "LP-07 CAM Charges -- HIGH" (with section ref if available)
            heading = f'{_esc_xml(pid)} {_esc_xml(pname)} -- '
            heading += f'<font color="{sev_color}"><b>{_esc_xml(display_sev)}</b></font>'
            if section_ref:
                heading += f'  <font color="#64748b">({_esc_xml(section_ref)})</font>'
            finding_els.append(Paragraph(heading, styles["FindingHeading"]))

            # Agreement pattern badge (e.g. "2-1 split")
            if agreement_pattern:
                is_unanimous = agreement_pattern.startswith("3-0") or agreement_pattern.startswith("2-0")
                if not is_unanimous:
                    finding_els.append(Paragraph(
                        f'<font color="#64748b">Evaluator agreement: {_esc_xml(agreement_pattern)}</font>',
                        styles["SmallMuted"],
                    ))

            # Body: risk_headline leads, then challenge_details or severity_reasoning
            body_parts = []
            if risk_headline:
                body_parts.append(risk_headline)
            if challenge_details:
                body_parts.append(challenge_details)
            elif sev_reasoning:
                body_parts.append(sev_reasoning)

            if body_parts:
                finding_els.append(Paragraph(
                    _esc_xml(" ".join(body_parts)),
                    styles["FindingBody"],
                ))

            # ── Evaluator votes block (matches screen's evaluator section) ──
            evaluator_verdicts = d.get("evaluator_verdicts", {})
            evaluator_reasoning = d.get("evaluator_reasoning", {})
            evaluator_confidences = d.get("evaluator_confidences", {})
            if evaluator_verdicts:
                finding_els.append(Paragraph("<b>Evaluator Votes:</b>", styles["FindingBody"]))
                for ev_key in ["A", "B", "C"]:
                    ev_verdict = evaluator_verdicts.get(ev_key, "")
                    if not ev_verdict or ev_verdict == "(evaluator unavailable)":
                        continue
                    ev_conf = evaluator_confidences.get(ev_key)
                    ev_reason = evaluator_reasoning.get(ev_key, "")
                    conf_str = f" ({ev_conf:.0%})" if ev_conf and ev_conf > 0 else ""
                    ev_color = "#c2410c" if ev_verdict == "DEVIATES" else "#16a34a" if ev_verdict == "CONFORMS" else "#64748b"
                    ev_line = (
                        f'  <b>{_esc_xml(ev_key)}:</b>  '
                        f'<font color="{ev_color}"><b>{_esc_xml(ev_verdict)}</b></font>'
                        f'{_esc_xml(conf_str)}'
                    )
                    finding_els.append(Paragraph(ev_line, styles["ClauseLabel"]))
                    if ev_reason and ev_reason.strip() != "(evaluator unavailable)":
                        # Truncate long reasoning to ~200 chars for PDF conciseness
                        short_reason = ev_reason.strip()
                        if len(short_reason) > 120:
                            short_reason = short_reason[:117] + "..."
                        finding_els.append(Paragraph(
                            f'<i>{_esc_xml(short_reason)}</i>',
                            styles["ClauseText"],
                        ))

            # Template vs Tenant language (matches screen's side-by-side view)
            if template_text or tenant_text:
                # Use AI interpretation note if available; otherwise show clean 2-sentence excerpt
                interpretation_note = d.get("interpretation_note", "")
                if interpretation_note and interpretation_note.strip():
                    # Strip markdown from interpretation note
                    clean_note = _sanitize_for_pdf(interpretation_note.strip())
                    finding_els.append(Paragraph(
                        f'<b>Interpretation:</b>  {_esc_xml(clean_note)}',
                        styles["ClauseText"],
                    ))
                else:
                    # Fall back to clean 2-sentence excerpt of tenant clause
                    if tenant_text:
                        sentences = [s.strip() for s in tenant_text.replace("\n", " ").split(".") if s.strip()]
                        excerpt = ". ".join(sentences[:2])
                        if excerpt and not excerpt.endswith("."):
                            excerpt += "."
                        if len(sentences) > 2:
                            excerpt += " [See annotated document for full clause text.]"
                        finding_els.append(Paragraph(
                            f'<b>Tenant Clause:</b>  {_esc_xml(excerpt)}',
                            styles["ClauseText"],
                        ))

            # Impact / severity reasoning (shown separately if challenge_details was present)
            if sev_reasoning and challenge_details:
                finding_els.append(Paragraph(
                    f'<b>Impact:</b>  {_esc_xml(sev_reasoning)}',
                    styles["FindingBody"],
                ))

            # Financial impact
            if financial_impact:
                finding_els.append(Paragraph(
                    f'<b>Financial Impact:</b>  {_esc_xml(financial_impact)}',
                    styles["FindingBody"],
                ))

            # Recommended action in italic
            if action:
                finding_els.append(Paragraph(
                    f"Recommendation: {_esc_xml(action)}",
                    styles["FindingAction"],
                ))
            if note_texts:
                finding_els.append(Paragraph("<b>Attorney Notes:</b>", styles["FindingBody"]))
                for note_text in note_texts:
                    finding_els.append(Paragraph(
                        f"&bull; {_esc_xml(note_text)}",
                        styles["ClauseText"],
                    ))

            # Fragility/rules omitted from client-facing PDF

            finding_els.append(Spacer(1, 6))

            # Add all finding elements — no KeepTogether to avoid large blank gaps
            elements.extend(finding_els)

    # ════════════════════════════════════════════════
    # LAST PAGE: Run Details
    # ════════════════════════════════════════════════

    elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0"),
                                spaceBefore=16, spaceAfter=8))
    elements.append(Paragraph("RUN DETAILS", styles["SynopsisHeading"]))
    elements.append(Spacer(1, 4))

    elements.append(Paragraph("Models Used:", styles["SmallMuted"]))

    extraction_model = models_used.get("extraction") or models_used.get("extractor", "")
    if extraction_model:
        elements.append(Paragraph(f"  Extraction: {_esc_xml(_model_name(extraction_model))}", styles["SmallMuted"]))
    if models_used.get("evaluator_a"):
        elements.append(Paragraph(f"  Evaluator A: {_esc_xml(_model_name(models_used['evaluator_a']))}", styles["SmallMuted"]))
    if models_used.get("evaluator_b"):
        elements.append(Paragraph(f"  Evaluator B: {_esc_xml(_model_name(models_used['evaluator_b']))}", styles["SmallMuted"]))
    if models_used.get("evaluator_c"):
        elements.append(Paragraph(f"  Evaluator C: {_esc_xml(_model_name(models_used['evaluator_c']))}", styles["SmallMuted"]))
    challenger_model = models_used.get("challenger", "")
    if challenger_model:
        elements.append(Paragraph(f"  Challenger: {_esc_xml(_model_name(challenger_model))}", styles["SmallMuted"]))
    severity_model = models_used.get("severity") or models_used.get("severity_assessor", "")
    if severity_model:
        elements.append(Paragraph(f"  Severity: {_esc_xml(_model_name(severity_model))}", styles["SmallMuted"]))

    elements.append(Spacer(1, 6))
    minutes = round(total_elapsed / 60, 1)
    elements.append(Paragraph(f"Processing: {total_api_calls} API calls total, {minutes} minutes", styles["SmallMuted"]))
    elements.append(Paragraph("Pipeline: CAM v2.5.3 -- Constrained Assertion Method", styles["SmallMuted"]))

    template_name = first_result.get("template_file", "Unknown")
    elements.append(Paragraph(f"Template file: {_esc_xml(template_name)}", styles["SmallMuted"]))

    elements.append(Spacer(1, 16))
    elements.append(Paragraph(
        "This report was generated by CAM (Constrained Assertion Method). "
        "Patent Pending. This is a diagnostic tool and does not constitute legal advice.",
        styles["Disclaimer"],
    ))

    doc.build(elements)
    logger.info(f"Combined synopsis PDF saved: {output_path}")
    return output_path
